### ISSUE TITLE
Sending trade offers?

### ISSUE THREAD

**Issue by Nefarious-** [Philipp15b/go-steam#22]
I've spent some time browsing the code and docs because it seems like quite a neat solution in all.

I couldn't, however, find any implementation to send trade offers; I might have just missed something, but I'm fairly certain there's nothing.

Can you confirm this?

Cheers.

**Comment by Philipp15b** [comment]
You're right, go-steam can't send trade offers.

Originally this wasn't implemented because the Steam Trade Offers API did not provide such a feature. I went ahead and implemented it with the usual Steam website calls earlier this year (but did not yet upload the changes) and literally a few days after, [Valve added a CAPTCHA to Steam Trading](http://www.valvetime.net/threads/steam-trading-implements-captcha-to-curb-outbreak-of-malware.245671/) and broke everything. Apparently there are exceptions for some bots, but I'd need some details on that.

**Comment by Nefarious-** [comment]
Ah nice, so the released branch is just being your dev branch due to obvious reasons?

They have changed it to a confirmation email, which you can disable via your privacy setting. So no more CAPTCHAs now.

**Comment by Philipp15b** [comment]
That option sounds good, the code simply assumes there's no CAPTCHA. I just pushed 482c4cc3b7e155a3f42be501e33fdd1b33939e36 which should fix this. The code's not really tested, so beware :)
