### ISSUE TITLE
Is there an event for knowing if the bot has sent a chat message?

### ISSUE THREAD

**Issue by Gacnt** [Philipp15b/go-steam#61]
I've checked 

```
ChatEnterEvent
ChatMsgEvent
ChatMemberInfoEvent
```

The only one that works for what I'm looking for is `ChatMsgEvent` the only problem is it only triggers on recieving a message and not on sending one

My problem is that I need to send a message to a friend and then remove them from friends list, the only problem is the remove friend happens before the chat message sends no matter what order they're in and I don't want to put in a `time.Sleep` so I was wondering if there was a way to listen for when my bot sends a chat message, and then act on that event to remove the friend from there. Any information would be great thanks.

**Comment by YellowOrWhite** [comment]
How do you know that remove friend happens before chat message is sent? Also, it would be helpful if you provide some background on exact problem.

**Comment by Philipp15b** [comment]
As long as you make sure you use the go-steam API consistently from your program (that is either from one goroutine only or you make sure yourself that your goroutines work correctly by always sending the message first and then unfriending) go-steam will also send those messages to Steam in exactly that order. 

That's because writing messages to the network happens only from exactly one goroutine in go-steam. The writer goroutine receives its messages through a channel which guarantees order.

So you can simply track chat message sending from your own program. 

If some packets are actually sent out of order by go-steam, that's a serious bug and I'll reopen this.
