### ISSUE TITLE
Last commit was in June, is this no longer being maintained or?

### ISSUE THREAD

**Issue by Gacnt** [Philipp15b/go-steam#63]
There is 9 valid pull requests, no commits have been sent in since June, and it doesn't seem anybody replies to any issues here anymore. Is this dead?

**Comment by Philipp15b** [comment]
This project was dead for a while, yes. Because I do not actively use go-steam myself anymore, I did not really keep up with Steam updates and, being busy, did not find the time to adequately respond to really useful input, both pull requests and issues.

I will however go through the active issues and pull requests in the next few days and will attempt to update go-steam. I'll try to keep maintaining go-steam more diligently (and much more frequently) in the future. Thank you for your help!
